apiVersion: apps/v1
kind: Deployment
metadata:
  name:  laken-web-app
  labels:
    app:  testing-example
spec:
  selector:
    matchLabels:
      app: testing-example
  replicas: 4
  template:
    metadata:
      labels:
        app:  testing-example
    spec:
      containers:
      - name:  laken-web-app
        image:  docker.io/woodl/design_image:latest
        ports:
        - containerPort:  80

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: default
spec:
  selector:
    app: testing-example
  type: NodePort
  ports:
  - name: my-service
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000
